service: api-with-eve

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  # allows us to serve the function locally
  - serverless-wsgi

custom:
  wsgi:
    app: handlers/app.app

provider:
  name: aws
  runtime: python3.8

functions:
  index:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'